apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nameserver-switcher.fullname" . }}-patterns
  labels:
    {{- include "nameserver-switcher.labels" . | nindent 4 }}
data:
  {{- if .Values.patterns.request }}
  REQUEST_PATTERNS: |
    {{- range .Values.patterns.request }}
    {{ . }}
    {{- end }}
  {{- else }}
  REQUEST_PATTERNS: ""
  {{- end }}
  {{- if .Values.patterns.cname }}
  CNAME_PATTERNS: |
    {{- range .Values.patterns.cname }}
    {{ . }}
    {{- end }}
  {{- else }}
  CNAME_PATTERNS: ""
  {{- end }}
