{{- if eq .Values.deploymentType "DaemonSet" }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "nameserver-switcher.fullname" . }}
  labels:
    {{- include "nameserver-switcher.labels" . | nindent 4 }}
    app.kubernetes.io/component: daemonset
spec:
  selector:
    matchLabels:
      {{- include "nameserver-switcher.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "nameserver-switcher.selectorLabels" . | nindent 8 }}
    spec:
      {{- include "nameserver-switcher.podSpec" . | nindent 6 }}
{{- end }}
